### ISSUE TITLE
Add colon symbol to TaskNamePattern

### ISSUE THREAD

**Issue by nsemikov** [goyek/goyek#153]
I'm want to be able for use colon in task names like `build:serviceName` and `build:all`

**Comment by pellared** [comment]
Are there any other characters that you would find useful?

Here is the current regex [`^[a-zA-Z0-9_][a-zA-Z0-9_-]*$`](https://pkg.go.dev/github.com/goyek/goyek#TaskNamePattern)

**Comment by pellared** [comment]
I tried to add it here: https://github.com/goyek/goyek/pull/154

Can you test `go get github.com/goyek/goyek@dcca3e9` and let me know if this fits your need? If so then I will release it soon.

**Comment by nsemikov** [comment]
I tested #155 `go get github.com/goyek/goyek@b3348db` - it works fine for me

**Comment by pellared** [comment]
Thanks. Tomorrow, I will release a new version.

Feel free to contribute even more 👍
