### ISSUE TITLE
How to structure goyek to prevent `unused (U1000)go-staticcheck`

### ISSUE THREAD

**Issue by dineshdh** [goyek/goyek#386]
## Description

go-staticcheck reports unused variable (`unused (U1000)go-staticcheck`). How do I structure the project so that this warning doesn't appear?

## Reproduction

<img width="135" alt="image" src="https://github.com/goyek/goyek/assets/5514771/b360b96d-31a2-40e3-8760-2cdd2442c4ec">
<br>
<img width="468" alt="image" src="https://github.com/goyek/goyek/assets/5514771/b3385396-c28d-4efd-93b6-aa7fecb5d15a">

## Environment

- OS: [e.g. Windows 10]
- Go version: [e.g. 1.13]
- goyek version: [e.g. 0.6.0]

**Comment by pellared** [comment]
You can change `var lint =`  to `var _ =`. Example: https://github.com/goyek/goyek/blob/main/build/ci.go#L5
