### ISSUE TITLE
Support sub commands and task specific flags

### ISSUE THREAD

**Issue by dineshdh** [goyek/goyek#389]
## Why

I would like to goyek to support sub commands and task specific flags. Perhaps this is already possible, just not sure how to do it.

e.g. 
sub commands
```
cobra add create
cobra add birthday
cobra add appointment
```

Also task specific flags as some falgs really don't apply to all tasks

**Comment by pellared** [comment]
You would try creating a https://pkg.go.dev/github.com/goyek/goyek/v2#Flow for each sub-command.

It is on you how to create them, but I think you try:
- creating your own code similar to this https://abhinavg.net/2022/08/13/flag-subcommand/
- using https://github.com/spf13/cobra
- using https://github.com/google/subcommands

**Comment by pellared** [comment]
@dineshdh, does it work for you? Can we close the issue?

**Comment by pellared** [comment]
Closing as unresponsive.
