### ISSUE TITLE
Runtime dependency resolution 

### ISSUE THREAD

**Issue by obfu5c8** [goyek/goyek#406]
Is there a way to defer dependency resolution until run/execute time?

## Why

I'm trying to build some re-usable tasks on top of goyek that my team can share between projects. Some of these tasks are somewhat dynamic in nature and their definitions/names etc depends on config supplied by the end user.

These configs are constructed in the root `func main()` prior to running `boot.Main()`. Where I'm running into difficulty is is the user defines custom tasks in the global scope in `main.go` then it's trying to resolve dependencies that don't exist yet (be ause they won't be created until `main()` is executed).

## What

Is there a way to make dependency resolution "just-in-time" i.e. not evaluated until just before the task stack is executed?

Since task names must be unique, perhaps a string task name could be supplied as a dep that gets resolved at the last minute, panic/fatal-ing if no task is defined with that particular name.

## Alternatives

I haven't tried it, but I assume some of this could be helped by creating dynamic tasks inside of an `init()` func in `main.go` instead of in `main()` but this still requires careful ordering of task definitions inside the file, requiring you to organise them in dependency order rather than semantically as makes sense to the user

For example, gnuMake accepts anything as a dependency and only resolves (or errors) at the last minute, meaning you're free to organise your Makefile in whatever order you like.

**Comment by pellared** [comment]
I think there are many ways you can achieve it

PTAL at https://github.com/goyek/demo for inspiration.

**Comment by pellared** [comment]
Please let me know if my suggestion helped or if you found out other convenient way to achieve what you needed.

I decided to make dependency registration "static" instead of "dynamic" as I feel it is less error-prone and avoids runtime errors.

**Comment by pellared** [comment]
@obfu5c8, any update?

**Comment by pellared** [comment]
Closing as not responsive.
