### ISSUE TITLE
Allow accessing task by Name from Flow

### ISSUE THREAD

**Issue by radTuti** [goyek/goyek#409]
## Why

Currently I want to be able to access task defined using a middleware generator to be used as Deps in other Tasks.

## What

The abiliry to access task by name so a new function so something like

```go
// Task returns a task based on its Name
func (f *Flow) Task(name string) *DefinedTask {
	snapshot := tasks[name}
	return &DefinedTask{snapshot, f}
}
```

## Alternatives

I have considered just naming the function but that results in duplications since I'm creating a middleware of commonly used tasks across various projects

## Other

N/A

**Comment by pellared** [comment]
Can you illustrate what the middleware is supposed to do?

Cannot you simply use https://pkg.go.dev/github.com/goyek/goyek/v2#Flow.Tasks?

**Comment by radTuti** [comment]
https://pkg.go.dev/github.com/goyek/goyek/v2#Flow.Tasks retunrs a list of tasks which is not indexed.

This is a condensed example of a middleware that is a bit of an extension of https://github.com/goyek/x/blob/main/boot/boot.go

// common/middleware.go

```go
package middleware

import (
    "github.com/goyek/goyek/v2"
    "github.com/goyek/x/boot"
)

func Main() {
    goyek.Define(goyek.Task {Name: "common-a"})
    goyek.Define(goyek.Task {Name: "common-b"})
    goyek.Define(goyek.Task {Name: "common-c"})

    // nice to have
    goyek.Define(goyek.Task {Name: "common-d", Deps: []*goyek.DefinedTasks{goyek.DefaultFlow.Task("common-b")} })

    boot.Main()
}
```

// projectA/build/main.go

```go
package main

import(
    ".../common"
)

var _ = goyek.Define(goyek.Task {Name: "first-task"})

var _ = goyek.Define(goyek.Task {Name: "second-task", Deps: []*goyek.DefinedTasks{goyek.DefaultFlow.Task("common-c")} })

func main() {
    common.Main()
}
```

Running `go run ./build --help` will list the follow 

```sh
Usage of build: [flags] [--] [tasks]
Tasks:
  common-a
  common-b
  common-c
  common-d          (depends on: common-b) 
  first-task
  second-task       (depends on: common-c)
Flags:
  -dry-run
        print all tasks without executing actions
  -long-run duration
        print when a task takes longer (default 1m0s)
  -no-color
        disable colorizing output
  -no-deps
        do not process dependencies
  -skip comma-separated tasks
        skip processing the comma-separated tasks
  -v    print all tasks as they are run
```

**Comment by pellared** [comment]
Why not making something like this in common/middleware.go:

```go
var C = goyek.Define(goyek.Task {Name: "common-c"})
```

so that you can later use it in projectA/build/main.go? It would be less error prone.

Also look at goyek/demo and goyek/workflow - demonstratation of sime reusability patterns.

**Comment by radTuti** [comment]
That was helpful, thank you
