### ISSUE TITLE
Update awesome-go listing

### ISSUE THREAD

**Issue by dertseha** [goyek/goyek#47]
Although GitHub maintains forwards from previous names/repositories, it is better to have the official name listed in awesome-go. Currently the listing still states the original name of the repository.

Change the listing in [this section](https://github.com/avelino/awesome-go#build-automation) from taskflow to goyek, to reflect the rebranding.

**Comment by pellared** [comment]
Created yesterday: https://github.com/avelino/awesome-go/pull/3592

But it is good to have it tracked here 👍

**Comment by pellared** [comment]
https://github.com/avelino/awesome-go/pull/3592 is merged.
