### ISSUE TITLE
Add wrapper scripts

### ISSUE THREAD

**Issue by pellared** [goyek/goyek#59]
Example: https://github.com/adamralph/bullseye#sample-wrapper-scripts

They could be used in GitHub workflow

**Comment by dertseha** [comment]
As noted in the PR: the scripts come down to a call of "go run build".
Do I understand you correctly, that they should be added to the readme file, similar to as shown in the sample?

**Comment by pellared** [comment]
> As noted in the PR: the scripts come down to a call of "go run build".
> Do I understand you correctly, that they should be added to the readme file, similar to as shown in the sample?

The convenience script can do more than just that. It can make sure that `goyek` can be run from any location. This is extremely helpful when developing in a multi-module Go repository.
