### ISSUE TITLE
Add working directory global parameter

### ISSUE THREAD

**Issue by pellared** [goyek/goyek#69]
Original discussion: https://github.com/goyek/goyek/pull/66#discussion_r631200348

## Problem

We want to support the following scenarios:
- multi-module repository
- separation of build dependencies in their own `go.mod`
- ability to run from any location
- get rid of (from `build/build.go`):
  ```go
   if err := os.Chdir(".."); err != nil {
   	fmt.Println(err)
   	os.Exit(goyek.CodeInvalidArgs)
   }
   ```
- `go run ./build/build.go` should still work

## Proposed solution

Add `wd` (which stands for "working directory") global parameter with `"."` as default value. This will allow using `go run` from any location (not only root). Moreover, the parameter can (but does not have to) be reused in the wrapper scripts.

It may be also good to make an abstraction for the global parameters. It does not have to be exported. The abstraction can be internal at this point.

**Comment by dertseha** [comment]
I would like an additional requirement: Default to practical settings for simple setup.
For example, I still want to be able to run the original command that got me interested: `go run ./build/build.go` from the CLI without any further things.
With the `-wd` approach, this would mean to default the parameter to `os.Getwd()`.

**Comment by pellared** [comment]
> With the `-wd` approach, this would mean to default the parameter to `os.Getwd()`.

The default can simply be `"."`. I have just tested it.

**Comment by dertseha** [comment]
All right.
